name: publish

on:
  push:
    branches:
      - main # Adjust the branch as needed

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Altacee Container Registry
        uses: docker/login-action@v1
        with:
          registry: acr.altacee.com
          username: rahulvk007
          password: ${{ secrets.ACR }}

      - name: Build the hello-docker Docker image
        run: docker build . -t acr.altacee.com/rahulvk007/rvk-nginxproxymanager:latest

      - name: Push the Docker image to Altacee Container Registry
        run: docker push acr.altacee.com/rahulvk007/rvk-nginxproxymanager:latest
